services:
  - type: web
    name: eishro-backend
    env: node
    region: frankfurt
    plan: starter
    buildCommand: cd backend && npm install --legacy-peer-deps && npm run build
    startCommand: cd backend && node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_PREFIX
        value: /api
      - key: DB_DIALECT
        value: postgres
      - key: DB_HOST
        value: db.pwkgwjzakgibztwsvbjf.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: @Dm1ns$$2025
      - key: DB_NAME
        value: postgres
      - key: DB_LOGGING
        value: "false"
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_change_this_in_production
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://final-platform-gamma.vercel.app
      - key: MOAMALAT_MID
        value: 10081014649
      - key: MOAMALAT_TID
        value: 99179395
      - key: MOAMALAT_SECRET
        value: 3a488a89b3f7993476c252f017c488bb
      - key: LOG_LEVEL
        value: info
